function AM_CoM = find_AM_CoM(t,I_1,I_2,l_1,l_MCD_1,l_MCD_2,m_1,m_2,omega_1,omega_2,th_1,th_2)
%find_AM_CoM
%    AM_CoM = find_AM_CoM(T,I_1,I_2,L_1,l_MCD_1,l_MCD_2,M_1,M_2,OMEGA_1,OMEGA_2,TH_1,TH_2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    01-Nov-2022 02:12:53

t2 = cos(th_1);
t3 = sin(th_1);
t4 = m_1+m_2;
t5 = omega_1+omega_2;
t6 = th_1+th_2;
t7 = l_1.*t2;
t8 = cos(t6);
t9 = l_1.*t3;
t10 = sin(t6);
t11 = l_MCD_1.*m_1.*t2;
t13 = l_MCD_1.*m_1.*t3;
t19 = 1.0./t4;
t12 = omega_1.*t7;
t14 = omega_1.*t9;
t15 = l_MCD_2.*t8;
t16 = omega_1.*t11;
t17 = l_MCD_2.*t10;
t18 = omega_1.*t13;
t20 = t5.*t15;
t21 = t5.*t17;
t22 = t7+t15;
t23 = t9+t17;
t24 = m_2.*t22;
t25 = m_2.*t23;
t26 = t12+t20;
t27 = t14+t21;
t28 = m_2.*t27;
t29 = m_2.*t26;
t30 = t11+t24;
t31 = t13+t25;
t32 = t18+t28;
t33 = t16+t29;
t34 = t19.*t30;
t35 = t19.*t31;
t36 = -t34;
t37 = -t35;
t38 = t19.*t33;
t39 = t19.*t32;
AM_CoM = m_1.*((t34-l_MCD_1.*t2).*(t38-l_MCD_1.*omega_1.*t2)+(t35-l_MCD_1.*t3).*(t39-l_MCD_1.*omega_1.*t3))+I_1.*omega_1+I_2.*t5+m_2.*((t22+t36).*(t26-t38)+(t23+t37).*(t27-t39));
