function AM_O = find_AM_O(t,I_1,I_2,l_1,l_MCD_1,l_MCD_2,m_1,m_2,omega_1,omega_2,th_1,th_2)
%find_AM_O
%    AM_O = find_AM_O(T,I_1,I_2,L_1,l_MCD_1,l_MCD_2,M_1,M_2,OMEGA_1,OMEGA_2,TH_1,TH_2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    01-Nov-2022 02:12:54

t2 = cos(th_1);
t3 = sin(th_1);
t4 = omega_1+omega_2;
t5 = th_1+th_2;
t6 = l_MCD_1.^2;
t7 = cos(t5);
t8 = sin(t5);
AM_O = I_1.*omega_1+I_2.*t4+m_2.*((l_1.*omega_1.*t2+l_MCD_2.*t4.*t7).*(l_1.*t2+l_MCD_2.*t7)+(l_1.*omega_1.*t3+l_MCD_2.*t4.*t8).*(l_1.*t3+l_MCD_2.*t8))+m_1.*(omega_1.*t2.^2.*t6+omega_1.*t3.^2.*t6);
