function [alpha_1,tau_2] = find_alpha_1_tau_2(I_1,I_2,alpha_2,g,l_1,l_MCD_1,l_MCD_2,m_1,m_2,omega_1,omega_2,tau_1,th_1,th_2)
%FIND_ALPHA_1_TAU_2
%    [ALPHA_1,TAU_2] = FIND_ALPHA_1_TAU_2(I_1,I_2,ALPHA_2,G,L_1,l_MCD_1,l_MCD_2,M_1,M_2,OMEGA_1,OMEGA_2,TAU_1,TH_1,TH_2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    01-Nov-2022 02:12:53

t2 = cos(th_1);
t3 = sin(th_1);
t4 = I_2.*alpha_2;
t5 = th_1+th_2;
t6 = l_1.^2;
t7 = l_MCD_1.^2;
t8 = l_MCD_2.^2;
t9 = omega_1.^2;
t10 = omega_2.^2;
t15 = -tau_1;
t11 = t2.^2;
t12 = t3.^2;
t13 = cos(t5);
t14 = sin(t5);
t18 = g.*l_1.*m_2.*t2;
t19 = g.*l_MCD_1.*m_1.*t2;
t16 = t13.^2;
t17 = t14.^2;
t20 = g.*l_MCD_2.*m_2.*t13;
t21 = m_2.*t6.*t11;
t22 = m_1.*t7.*t11;
t23 = m_2.*t6.*t12;
t24 = m_1.*t7.*t12;
t25 = l_1.*l_MCD_2.*m_2.*t2.*t13.*2.0;
t26 = l_1.*l_MCD_2.*m_2.*t3.*t14.*2.0;
t27 = alpha_2.*l_1.*l_MCD_2.*m_2.*t2.*t13;
t29 = alpha_2.*l_1.*l_MCD_2.*m_2.*t3.*t14;
t33 = l_1.*l_MCD_2.*m_2.*t3.*t10.*t13;
t34 = l_1.*l_MCD_2.*m_2.*t2.*t10.*t14;
t35 = l_1.*l_MCD_2.*m_2.*omega_1.*omega_2.*t3.*t13.*2.0;
t36 = l_1.*l_MCD_2.*m_2.*omega_1.*omega_2.*t2.*t14.*2.0;
t28 = m_2.*t8.*t16;
t30 = m_2.*t8.*t17;
t37 = -t36;
t38 = -t34;
t31 = alpha_2.*t28;
t32 = alpha_2.*t30;
t39 = I_1+I_2+t21+t22+t23+t24+t25+t26+t28+t30;
t40 = 1.0./t39;
t41 = t4+t15+t18+t19+t20+t27+t29+t31+t32+t33+t35+t37+t38;
alpha_1 = -t40.*t41;
if nargout > 1
    tau_2 = t4+t20+t31+t32-t40.*t41.*(I_2+t28+t30+l_1.*l_MCD_2.*m_2.*t2.*t13+l_1.*l_MCD_2.*m_2.*t3.*t14)+l_1.*l_MCD_2.*m_2.*t2.*t9.*t14-l_1.*l_MCD_2.*m_2.*t3.*t9.*t13;
end
