function a_CoM_whole = find_a_CoM_whole(alpha_1,alpha_2,l_1,l_MCD_1,l_MCD_2,m_1,m_2,omega_1,omega_2,th_1,th_2)
%find_a_CoM_whole
%    a_CoM_whole = find_a_CoM_whole(ALPHA_1,ALPHA_2,L_1,l_MCD_1,l_MCD_2,M_1,M_2,OMEGA_1,OMEGA_2,TH_1,TH_2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    01-Nov-2022 02:12:53

t2 = cos(th_1);
t3 = sin(th_1);
t4 = alpha_1+alpha_2;
t5 = m_1+m_2;
t6 = omega_1+omega_2;
t7 = th_1+th_2;
t8 = omega_1.^2;
t9 = cos(t7);
t10 = sin(t7);
t11 = t6.^2;
t12 = 1.0./t5;
a_CoM_whole = [-t12.*(m_1.*(alpha_1.*l_MCD_1.*t3+l_MCD_1.*t2.*t8)+m_2.*(alpha_1.*l_1.*t3+l_1.*t2.*t8+l_MCD_2.*t4.*t10+l_MCD_2.*t9.*t11)),t12.*(m_1.*(alpha_1.*l_MCD_1.*t2-l_MCD_1.*t3.*t8)+m_2.*(alpha_1.*l_1.*t2-l_1.*t3.*t8+l_MCD_2.*t4.*t9-l_MCD_2.*t10.*t11))];
