function vx_CoM_whole = find_vx_CoM_whole(l_1,l_MCD_1,l_MCD_2,m_1,m_2,omega_1,omega_2,th_1,th_2)
%find_vx_CoM_whole
%    vx_CoM_whole = find_vx_CoM_whole(L_1,l_MCD_1,l_MCD_2,M_1,M_2,OMEGA_1,OMEGA_2,TH_1,TH_2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    01-Nov-2022 02:12:42

t2 = sin(th_1);
vx_CoM_whole = -(m_2.*(l_1.*omega_1.*t2+l_MCD_2.*sin(th_1+th_2).*(omega_1+omega_2))+l_MCD_1.*m_1.*omega_1.*t2)./(m_1+m_2);
