function dL_CoM = find_dL_CoM(l_1,l_MCD_1,l_MCD_2,m_1,m_2,omega_1,omega_2,th_1,th_2)
%find_dL_CoM
%    dL_CoM = find_dL_CoM(L_1,l_MCD_1,l_MCD_2,M_1,M_2,OMEGA_1,OMEGA_2,TH_1,TH_2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    01-Nov-2022 02:13:02

t2 = cos(th_1);
t3 = sin(th_1);
t4 = m_1+m_2;
t5 = omega_1+omega_2;
t6 = th_1+th_2;
t7 = l_1.*t2;
t8 = cos(t6);
t9 = l_1.*t3;
t10 = sin(t6);
t11 = l_MCD_1.*m_1.*t2;
t12 = l_MCD_1.*m_1.*t3;
t15 = 1.0./t4.^2;
t13 = l_MCD_2.*t8;
t14 = l_MCD_2.*t10;
t16 = t7+t13;
t17 = t9+t14;
t18 = m_2.*t16;
t19 = m_2.*t17;
t20 = t11+t18;
t21 = t12+t19;
dL_CoM = ((t15.*t21.*(omega_1.*t11+m_2.*(omega_1.*t7+t5.*t13)).*2.0-t15.*t20.*(omega_1.*t12+m_2.*(omega_1.*t9+t5.*t14)).*2.0).*1.0./sqrt(t15.*t20.^2+t15.*t21.^2))./2.0;
