function [tau_1,tau_2] = find_tau(I_1,I_2,alpha_1,alpha_2,g,l_1,l_MCD_1,l_MCD_2,m_1,m_2,omega_1,omega_2,th_1,th_2)
%FIND_TAU
%    [TAU_1,TAU_2] = FIND_TAU(I_1,I_2,ALPHA_1,ALPHA_2,G,L_1,l_MCD_1,l_MCD_2,M_1,M_2,OMEGA_1,OMEGA_2,TH_1,TH_2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    01-Nov-2022 02:12:53

t2 = cos(th_1);
t3 = sin(th_1);
t4 = I_2.*alpha_1;
t5 = I_2.*alpha_2;
t6 = th_1+th_2;
t7 = l_1.^2;
t8 = l_MCD_1.^2;
t9 = l_MCD_2.^2;
t10 = omega_1.^2;
t11 = omega_2.^2;
t12 = t2.^2;
t13 = t3.^2;
t14 = cos(t6);
t15 = sin(t6);
t16 = t14.^2;
t17 = t15.^2;
t18 = g.*l_MCD_2.*m_2.*t14;
t19 = alpha_1.*m_2.*t9.*t16;
t20 = alpha_2.*m_2.*t9.*t16;
t21 = alpha_1.*m_2.*t9.*t17;
t22 = alpha_2.*m_2.*t9.*t17;
tau_1 = t4+t5+t18+t19+t20+t21+t22+I_1.*alpha_1+g.*l_1.*m_2.*t2+g.*l_MCD_1.*m_1.*t2+alpha_1.*m_1.*t8.*t12+alpha_1.*m_2.*t7.*t12+alpha_1.*m_1.*t8.*t13+alpha_1.*m_2.*t7.*t13-l_1.*l_MCD_2.*m_2.*t2.*t11.*t15+l_1.*l_MCD_2.*m_2.*t3.*t11.*t14+alpha_1.*l_1.*l_MCD_2.*m_2.*t2.*t14.*2.0+alpha_2.*l_1.*l_MCD_2.*m_2.*t2.*t14+alpha_1.*l_1.*l_MCD_2.*m_2.*t3.*t15.*2.0+alpha_2.*l_1.*l_MCD_2.*m_2.*t3.*t15-l_1.*l_MCD_2.*m_2.*omega_1.*omega_2.*t2.*t15.*2.0+l_1.*l_MCD_2.*m_2.*omega_1.*omega_2.*t3.*t14.*2.0;
if nargout > 1
    tau_2 = t4+t5+t18+t19+t20+t21+t22+l_1.*l_MCD_2.*m_2.*t2.*t10.*t15-l_1.*l_MCD_2.*m_2.*t3.*t10.*t14+alpha_1.*l_1.*l_MCD_2.*m_2.*t2.*t14+alpha_1.*l_1.*l_MCD_2.*m_2.*t3.*t15;
end
