function L_CoM = find_L_CoM(l_1,l_MCD_1,l_MCD_2,m_1,m_2,th_1,th_2)
%find_L_CoM
%    L_CoM = find_L_CoM(L_1,l_MCD_1,l_MCD_2,M_1,M_2,TH_1,TH_2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    01-Nov-2022 02:13:01

t2 = cos(th_1);
t3 = sin(th_1);
t4 = m_1+m_2;
t5 = th_1+th_2;
t6 = 1.0./t4.^2;
L_CoM = sqrt(t6.*(m_2.*(l_1.*t2+l_MCD_2.*cos(t5))+l_MCD_1.*m_1.*t2).^2+t6.*(m_2.*(l_1.*t3+l_MCD_2.*sin(t5))+l_MCD_1.*m_1.*t3).^2);
