function v_CoM_whole = find_v_CoM_whole(l_1,l_MCD_1,l_MCD_2,m_1,m_2,omega_1,omega_2,th_1,th_2)
%find_v_CoM_whole
%    v_CoM_whole = find_v_CoM_whole(L_1,l_MCD_1,l_MCD_2,M_1,M_2,OMEGA_1,OMEGA_2,TH_1,TH_2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    01-Nov-2022 02:12:42

t2 = cos(th_1);
t3 = sin(th_1);
t4 = m_1+m_2;
t5 = omega_1+omega_2;
t6 = th_1+th_2;
t7 = 1.0./t4;
v_CoM_whole = [-t7.*(m_2.*(l_MCD_2.*t5.*sin(t6)+l_1.*omega_1.*t3)+l_MCD_1.*m_1.*omega_1.*t3),t7.*(m_2.*(l_MCD_2.*t5.*cos(t6)+l_1.*omega_1.*t2)+l_MCD_1.*m_1.*omega_1.*t2)];
