function Inertia_CoM = find_Inertia_CoM(I_1,I_2,l_1,l_MCD_1,l_MCD_2,m_1,m_2,th_1,th_2)
%find_Inertia_CoM
%    Inertia_CoM = find_Inertia_CoM(I_1,I_2,L_1,l_MCD_1,l_MCD_2,M_1,M_2,TH_1,TH_2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    01-Nov-2022 02:13:01

t2 = cos(th_1);
t3 = sin(th_1);
t4 = m_1+m_2;
t5 = th_1+th_2;
t6 = l_1.*t2;
t7 = cos(t5);
t8 = l_1.*t3;
t9 = sin(t5);
t10 = l_MCD_1.*m_1.*t2;
t11 = l_MCD_1.*m_1.*t3;
t14 = 1.0./t4;
t12 = l_MCD_2.*t7;
t13 = l_MCD_2.*t9;
t15 = t6+t12;
t16 = t8+t13;
t17 = m_2.*t15;
t18 = m_2.*t16;
t19 = t10+t17;
t20 = t11+t18;
t21 = t14.*t19;
t22 = t14.*t20;
t23 = -t21;
t24 = -t22;
Inertia_CoM = I_1+I_2+m_1.*((t21-l_MCD_1.*t2).^2+(t22-l_MCD_1.*t3).^2)+m_2.*((t15+t23).^2+(t16+t24).^2);
